name: Test app

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*

jobs:
  test_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      
      - name: Fetch required Go modules
        run:  go mod download
      
      - name: Install swagger & build docs
        run: sh scripts/swagger.sh

      - name: Test app
        run: go test -v

      - name: Try build
        run:  go build -v ./...
